"""Builds the laptop bundle: the bridge, pre-configured to talk to this server.

The point is to remove the hand-editing step. The download contains a
`config.toml` already pointing at this server, so the laptop side is unzip,
run setup, pair, scan for the strap, go.

The bundle deliberately carries **no credential**. It used to embed the shared
ingest token, which made the download itself a secret to protect; now the
laptop claims its own key with a short-lived pairing code, so what ships here
is only code and an address. The endpoint stays gated anyway -- see
`download_allowed` -- because there is no reason to serve it to the internet.
"""

from __future__ import annotations

import io
import ipaddress
import os
import zipfile
from pathlib import Path
from typing import Any

BUNDLE_ROOT = Path(os.environ.get("BUNDLE_ROOT", Path(__file__).resolve().parents[2]))

# Directories copied verbatim into the zip.
INCLUDE_DIRS = ("whoop_bridge", "tray", "windows")
INCLUDE_FILES = ("pyproject.toml", "requirements.txt")
SKIP_SUFFIXES = (".pyc", ".pyo", ".db", ".db-wal", ".db-shm", ".log")
SKIP_DIRS = {"__pycache__", ".venv", "venv", ".git", "build", "dist"}


def download_allowed(headers: dict[str, str], client_host: str | None) -> tuple[bool, str]:
    """Decide whether this request may download the bundle.

    Behind the tunnel, cloudflared sets `CF-Connecting-IP`, and Cloudflare
    Access sets `Cf-Access-Authenticated-User-Email` once a person has logged
    in at the edge. So:

      * arrived via Cloudflare -> require the Access header
      * arrived directly       -> require a private/loopback client (LAN setup)

    This trusts headers from the local reverse proxy, which is sound only
    because the app binds to 127.0.0.1 and nothing but cloudflared can reach
    it. Do not publish the port directly.
    """
    mode = os.environ.get("SETUP_DOWNLOAD", "on").strip().lower()
    if mode in ("off", "0", "false", "no"):
        return False, "The setup download is disabled (SETUP_DOWNLOAD=off)."
    if mode == "open":
        return True, "open"

    lower = {k.lower(): v for k, v in headers.items()}
    via_cloudflare = "cf-connecting-ip" in lower

    if via_cloudflare:
        if lower.get("cf-access-authenticated-user-email"):
            return True, "cloudflare-access"
        return False, (
            "This download is only served to a request Cloudflare Access has "
            "authenticated. Put an Access application in front of this hostname, "
            "or fetch it from the server's LAN address.")

    if _is_private(client_host):
        return True, "private-network"
    return False, (
        "This request did not come from Cloudflare Access or a private network "
        "address.")


def _is_private(host: str | None) -> bool:
    if not host:
        return False
    try:
        ip = ipaddress.ip_address(host)
    except ValueError:
        return False
    return ip.is_private or ip.is_loopback or ip.is_link_local


def public_base_url(headers: dict[str, str], fallback: str) -> str:
    """The URL the laptop should post to, as seen from outside."""
    lower = {k.lower(): v for k, v in headers.items()}
    host = lower.get("x-forwarded-host") or lower.get("host")
    if not host:
        return fallback.rstrip("/")
    proto = lower.get("x-forwarded-proto")
    if not proto:
        # Anything arriving through the tunnel is https on the public side.
        proto = "https" if "cf-connecting-ip" in lower else "http"
    return f"{proto}://{host}"


def render_config(base_url: str, token: str, cf_id: str = "", cf_secret: str = "") -> str:
    """A config.toml already pointing at this server."""
    return f'''# Generated by your Strap server -- already pointing at it.
# The only thing missing is your strap's Bluetooth address (step 2 below).
#
# Two things to fill in, both from the app:
#   1. whoop-bridge pair --code XXXX-XXXX   (Settings -> Connect a laptop)
#   2. whoop-bridge scan                    (then paste the address below)
#
# After pairing this file holds a token that can write to your server. Treat it
# as a password from then on: do not commit it or share it.

[device]
# Run:  .\\.venv\\Scripts\\whoop-bridge.exe scan
# then paste the address here. Un-pair the strap from the WHOOP phone app
# first -- it only talks to one device at a time.
address = ""

live_hr = true
backfill = true
ack_and_trim = true
backfill_interval = 900
include_imu = false

[forward]
# Filled in by `whoop-bridge pair` -- see step 2 below. Nothing secret ships
# in this download; the token is issued to this laptop when it pairs, and
# revoking it later does not disturb any other laptop.
forward_url = "{base_url}/ingest"
forward_token = ""
hmac_secret = ""

# Cloudflare Access service token. Needed when the server sits behind Access:
# the bridge is not a browser and cannot complete an interactive login.
cf_access_client_id = "{cf_id}"
cf_access_client_secret = "{cf_secret}"

batch_size = 50
forward_interval = 5.0
verify_tls = true

# Keep this bridge current from the server. Updates are verified against the
# digest the server declares and applied at the next start, never mid-sync.
# The server can also push behaviour settings (intervals, log level) -- but
# never this file's address or tokens.
auto_update = true
update_check_interval = 3600.0

[storage]
spool_path = "whoop-spool.db"
spool_max_rows = 500000

[logging]
log_level = "INFO"
log_file = "whoop-bridge.log"
'''


QUICKSTART = """# Strap - laptop setup

This came from your own server and already knows its address. Two commands and
you are done: one to pair this laptop to your account, one to find your strap.

Nothing secret is in this download. The key is issued to this laptop when it
pairs, and you can revoke it from the app without touching any other laptop.

## 1. Install

In this folder, in PowerShell (Administrator is NOT needed):

    powershell -ExecutionPolicy Bypass -File windows\\setup.ps1

That needs Python 3.11+ from python.org (tick "Add to PATH" when installing).

## 2. Pair this laptop

In the app, open **Settings -> Connect a laptop**. It shows a code. Then:

    .\\.venv\\Scripts\\whoop-bridge.exe pair --code XXXX-XXXX

The code works once and expires after about fifteen minutes; ask for another
if it lapses.

(The one-file `Strap.exe` does steps 1-3 in a window instead, and needs no
Python at all. These instructions are for the source install.)

## 3. Find your strap

**Un-pair the strap from the WHOOP phone app first**, and remove it from that
phone's Bluetooth settings. It bonds to one device at a time, so the laptop
will not see it otherwise.

    .\\.venv\\Scripts\\whoop-bridge.exe scan

Paste the address it prints into `address` in `config.toml`.

## 4. Run it

Tray app (recommended):

    .\\.venv\\Scripts\\pip.exe install -e ".[tray]"
    .\\.venv\\Scripts\\pythonw.exe -m tray.whoop_tray

Or headless, starting automatically at logon:

    .\\windows\\install-task.ps1
    Start-ScheduledTask -TaskName WhoopBridge

Then open your server's URL on this laptop or your phone.

## If pairing cannot reach the server

A 302 or 403 means the server is behind Cloudflare Access, which the bridge
cannot log in to interactively. Put a service token into
`cf_access_client_id` / `cf_access_client_secret` in `config.toml` and pair
again.

## Note

After pairing, `config.toml` holds this laptop's key. Treat it as a password
from then on: do not commit it or share this folder.
"""


def build_zip(base_url: str, token: str, cf_id: str = "", cf_secret: str = "",
              root: Path | None = None) -> bytes:
    """Zip the laptop half plus a generated config and quickstart."""
    root = root or BUNDLE_ROOT
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for name in INCLUDE_DIRS:
            base = root / name
            if not base.is_dir():
                continue
            for path in sorted(base.rglob("*")):
                if not path.is_file():
                    continue
                if path.suffix in SKIP_SUFFIXES:
                    continue
                if SKIP_DIRS & set(path.relative_to(root).parts):
                    continue
                z.write(path, f"strap-laptop/{path.relative_to(root)}")
        for name in INCLUDE_FILES:
            path = root / name
            if path.is_file():
                z.write(path, f"strap-laptop/{name}")
        z.writestr("strap-laptop/config.toml",
                   render_config(base_url, token, cf_id, cf_secret))
        z.writestr("strap-laptop/START-HERE.md", QUICKSTART)
    return buf.getvalue()


def bundle_status(root: Path | None = None) -> dict[str, Any]:
    root = root or BUNDLE_ROOT
    present = [n for n in INCLUDE_DIRS if (root / n).is_dir()]
    return {"root": str(root), "present": present,
            "ready": set(present) == set(INCLUDE_DIRS)}
