"""Builds the laptop bundle: the bridge, pre-configured to talk to this server.

The point is to remove the hand-editing step. The download contains a
`config.toml` already filled in with this server's URL and ingest token, so the
laptop side is unzip, run setup, scan for the strap, go.

That also means **the bundle contains a live credential**. Anyone who downloads
it can post data to this server. The endpoint is therefore gated -- see
`download_allowed`.
"""

from __future__ import annotations

import io
import ipaddress
import os
import zipfile
from pathlib import Path
from typing import Any

BUNDLE_ROOT = Path(os.environ.get("BUNDLE_ROOT", Path(__file__).resolve().parents[2]))

# Directories copied verbatim into the zip.
INCLUDE_DIRS = ("whoop_bridge", "tray", "windows")
INCLUDE_FILES = ("pyproject.toml", "requirements.txt")
SKIP_SUFFIXES = (".pyc", ".pyo", ".db", ".db-wal", ".db-shm", ".log")
SKIP_DIRS = {"__pycache__", ".venv", "venv", ".git", "build", "dist"}


def download_allowed(headers: dict[str, str], client_host: str | None) -> tuple[bool, str]:
    """Decide whether this request may download the bundle.

    Behind the tunnel, cloudflared sets `CF-Connecting-IP`, and Cloudflare
    Access sets `Cf-Access-Authenticated-User-Email` once a person has logged
    in at the edge. So:

      * arrived via Cloudflare -> require the Access header
      * arrived directly       -> require a private/loopback client (LAN setup)

    This trusts headers from the local reverse proxy, which is sound only
    because the app binds to 127.0.0.1 and nothing but cloudflared can reach
    it. Do not publish the port directly.
    """
    mode = os.environ.get("SETUP_DOWNLOAD", "on").strip().lower()
    if mode in ("off", "0", "false", "no"):
        return False, "The setup download is disabled (SETUP_DOWNLOAD=off)."
    if mode == "open":
        return True, "open"

    lower = {k.lower(): v for k, v in headers.items()}
    via_cloudflare = "cf-connecting-ip" in lower

    if via_cloudflare:
        if lower.get("cf-access-authenticated-user-email"):
            return True, "cloudflare-access"
        return False, (
            "This download hands out your ingest token, so it is only served to a "
            "request Cloudflare Access has authenticated. Put an Access application "
            "in front of this hostname, or fetch it from the server's LAN address.")

    if _is_private(client_host):
        return True, "private-network"
    return False, (
        "This download hands out your ingest token and this request did not come "
        "from Cloudflare Access or a private network address.")


def _is_private(host: str | None) -> bool:
    if not host:
        return False
    try:
        ip = ipaddress.ip_address(host)
    except ValueError:
        return False
    return ip.is_private or ip.is_loopback or ip.is_link_local


def public_base_url(headers: dict[str, str], fallback: str) -> str:
    """The URL the laptop should post to, as seen from outside."""
    lower = {k.lower(): v for k, v in headers.items()}
    host = lower.get("x-forwarded-host") or lower.get("host")
    if not host:
        return fallback.rstrip("/")
    proto = lower.get("x-forwarded-proto")
    if not proto:
        # Anything arriving through the tunnel is https on the public side.
        proto = "https" if "cf-connecting-ip" in lower else "http"
    return f"{proto}://{host}"


def render_config(base_url: str, token: str, cf_id: str = "", cf_secret: str = "") -> str:
    """A config.toml already pointing at this server."""
    return f'''# Generated by your Strap server -- already pointing at it.
# The only thing missing is your strap's Bluetooth address (step 2 below).
#
# This file contains a token that can write to your server. Treat it as a
# password: do not commit it or share it.

[device]
# Run:  .\\.venv\\Scripts\\whoop-bridge.exe scan
# then paste the address here. Un-pair the strap from the WHOOP phone app
# first -- it only talks to one device at a time.
address = ""

live_hr = true
backfill = true
ack_and_trim = true
backfill_interval = 900
include_imu = false

[forward]
forward_url = "{base_url}/ingest"
forward_token = "{token}"
hmac_secret = ""

# Cloudflare Access service token. Needed when the server sits behind Access:
# the bridge is not a browser and cannot complete an interactive login.
cf_access_client_id = "{cf_id}"
cf_access_client_secret = "{cf_secret}"

batch_size = 50
forward_interval = 5.0
verify_tls = true

# Keep this bridge current from the server. Updates are verified against the
# digest the server declares and applied at the next start, never mid-sync.
# The server can also push behaviour settings (intervals, log level) -- but
# never this file's address or tokens.
auto_update = true
update_check_interval = 3600.0

[storage]
spool_path = "whoop-spool.db"
spool_max_rows = 500000

[logging]
log_level = "INFO"
log_file = "whoop-bridge.log"
'''


QUICKSTART = """# Strap - laptop setup

This bundle came from your own server and is already configured to talk to it.
`config.toml` has the address and token filled in; you only need to add your
strap.

## 1. Install

Right-click PowerShell, Run as Administrator is NOT needed. In this folder:

    powershell -ExecutionPolicy Bypass -File windows\\setup.ps1

That needs Python 3.11+ installed from python.org (tick "Add to PATH").

## 2. Find your strap

**Un-pair the strap from the WHOOP phone app first**, and remove it from that
phone's Bluetooth settings. It bonds to one device at a time, so the laptop
will not see it otherwise.

    .\\.venv\\Scripts\\whoop-bridge.exe scan

Paste the address it prints into `address` in `config.toml`.

## 3. Check the connection

    .\\.venv\\Scripts\\whoop-bridge.exe test-endpoint

A 2xx means the laptop can reach your server. If you get a 302 or 403, the
server is behind Cloudflare Access and needs a service token - see
`cf_access_client_id` in `config.toml`.

## 4. Run it

Tray app (recommended):

    .\\.venv\\Scripts\\pip.exe install -e ".[tray]"
    .\\.venv\\Scripts\\pythonw.exe -m tray.whoop_tray

Or headless, starting automatically at logon:

    .\\windows\\install-task.ps1
    Start-ScheduledTask -TaskName WhoopBridge

Then open your server's URL in a browser, on this laptop or your phone.

## Note

`config.toml` holds a token that can write to your server. Do not commit it or
share this folder.
"""


def build_zip(base_url: str, token: str, cf_id: str = "", cf_secret: str = "",
              root: Path | None = None) -> bytes:
    """Zip the laptop half plus a generated config and quickstart."""
    root = root or BUNDLE_ROOT
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for name in INCLUDE_DIRS:
            base = root / name
            if not base.is_dir():
                continue
            for path in sorted(base.rglob("*")):
                if not path.is_file():
                    continue
                if path.suffix in SKIP_SUFFIXES:
                    continue
                if SKIP_DIRS & set(path.relative_to(root).parts):
                    continue
                z.write(path, f"strap-laptop/{path.relative_to(root)}")
        for name in INCLUDE_FILES:
            path = root / name
            if path.is_file():
                z.write(path, f"strap-laptop/{name}")
        z.writestr("strap-laptop/config.toml",
                   render_config(base_url, token, cf_id, cf_secret))
        z.writestr("strap-laptop/START-HERE.md", QUICKSTART)
    return buf.getvalue()


def bundle_status(root: Path | None = None) -> dict[str, Any]:
    root = root or BUNDLE_ROOT
    present = [n for n in INCLUDE_DIRS if (root / n).is_dir()]
    return {"root": str(root), "present": present,
            "ready": set(present) == set(INCLUDE_DIRS)}
